language: python
python:
  - "3.6"
# command to run tests
script: 
  pip install -r requirements.txt
  pytest 

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    branch: master
    tag: true