# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Deps
      run: |
        python -m pip install -U pip
        python -m pip install poetry
        python -m poetry install
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names                                                                               
         poetry run flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics                                                                                  
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide                                                                      
         poetry run flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 
    - name: Test
      run: |
          poetry run pytest

